#!/bin/bash
#
DWORD=$(cat $(pwd)/dd_word) # Dictionary
A="" # Starting true
B="" # Load
# Funciton bruteforce
func_one ()
{
	if [[ -z "$A" && -z "$B" ]]
	then
		for word in $DWORD # Start bruteforce one word
		do
			echo $word
		done
		func_two # Start bruteforce two a words
	elif [[ -z "$B"  ]]
	then
		for word in $DWORD
		do
			echo "$A$word" 
		done
		func_tree
	else
		for word in $DWORD 
		do 
			echo $B$A$word 
		done
	fi
}
# Function 2xbruteforce 
func_two () 
{
	for A in $DWORD
	do
		echo "  [][$A][]"; func_one
	done
}
# Funcion 3xbruteforce
func_tree ()
{
	for ((i=1; i<3; i++))
	do
		for B in $DWORD
		do
			for A in $DWORD
			do
			echo "[$i][][$B][][]"; func_two
		done 
	done
done
}
#
func_one
