#!/bin/bash
#
DWORD=$(cat $(pwd)/dd_word) # Dictionary
A="" # Null
B="" # Null
# Funciton bruteforce
func_one ()
{
	if [[ -z "$A" && -z "$B" ]] # Start brute else A=0 and B=0
	then
		for word in $DWORD # select one word
		do
			echo $word
		done
		func_two # Func select two a words
	elif [[ -z "$B"  ]] # Start 2xbrute else B!=0
	then
		for word in $DWORD
		do
			echo "$A$word" 
		done
	else 
		for word in $DWORD 
		do 
			echo $B$A$word 
		done
	fi
}
# Function 2xbruteforce 
func_two () 
{
	for A in $DWORD
	do
		echo "  [][$A][]"; func_one # Launch second condition
	done
}
# Funcion 3xbruteforce
func_tree ()
{
	for B in $DWORD
	do
		for A in $DWORD
		do
			echo "[][$B][][$A][]"; func_one # Launch third condition
		done 
	done
}
#
func_one
func_tree
